### ISSUE TITLE
Can't run games via Docker with newer Ubuntu versions

### ISSUE THREAD

**Issue by skytreader** [skytreader/PyGame-Objects#45]
Distro: Ubuntu 20.04.1 LTS

Sample log:

```
$ ./duckrunner demo.snake.game
2020-08-31 12:44:56,413 WARNING Can't open a file handler. Logs won't be written to file.
No protocol specified
No protocol specified
No protocol specified
No protocol specified
Traceback (most recent call last):
  File "/app/components/core.py", line 166, in go
    self.loop_events.loop_setup()
  File "/app/components/core.py", line 517, in loop_setup
    self.configurable_setup()
  File "/app/components/core.py", line 501, in configurable_setup
    window = self.invoke_window(self.game_screen.screen_dimensions)
  File "/app/components/core.py", line 473, in invoke_window
    self.__window = pygame.display.set_mode(window_size)
pygame.error: No available video device
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame init
```

In general, running via GUIs via Docker seems different now.

**Comment by skytreader** [comment]
Possible reference: http://wiki.ros.org/docker/Tutorials/GUI

**Comment by skytreader** [comment]
See also: https://askubuntu.com/a/1250850/36150
